Make sure GPU is enabled
Runtime -> Change Runtime Type -> Hardware Accelerator -> GPU

In [14]:
from IPython.display import Audio
from IPython.utils import io
from synthesizer.inference import Synthesizer
from encoder import inference as encoder
from vocoder import inference as vocoder
from pathlib import Path
import numpy as np
import librosa
encoder_weights = Path("encoder/saved_models/pretrained.pt")
vocoder_weights = Path("vocoder/saved_models/pretrained/pretrained.pt")
syn_dir = Path("synthesizer/saved_models/logs-pretrained/taco_pretrained")
encoder.load_model(encoder_weights)
synthesizer = Synthesizer(syn_dir)
vocoder.load_model(vocoder_weights)

Loaded encoder "pretrained.pt" trained to step 1564501
Found synthesizer "pretrained" trained to step 278000
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt


In [15]:
#@title Deep vocoder
def synth():
  text = "This is being said in my own voice.  The computer has learned to do an impression of me." #@param {type:"string"}
  print("Now recording for 10 seconds, say what you will...")
#   record(10)
  print("Audio recording complete")
  in_fpath =r"C:\Users\pedestrian\Desktop\re-voiceprint\human\lu1.m4a"
  reprocessed_wav = encoder.preprocess_wav(in_fpath)
  original_wav, sampling_rate = librosa.load(in_fpath)
  preprocessed_wav = encoder.preprocess_wav(original_wav, sampling_rate)
  embed = encoder.embed_utterance(preprocessed_wav)
  print("Synthesizing new audio...")
  with io.capture_output() as captured:
    specs = synthesizer.synthesize_spectrograms([text], [embed])
  generated_wav = vocoder.infer_waveform(specs[0])
  generated_wav = np.pad(generated_wav, (0, synthesizer.sample_rate), mode="constant")
  display(Audio(generated_wav, rate=synthesizer.sample_rate))

In [16]:
synth()

Now recording for 10 seconds, say what you will...
Audio recording complete
Synthesizing new audio...
INFO:tensorflow:Restoring parameters from synthesizer\saved_models\logs-pretrained\taco_pretrained\tacotron_model.ckpt-278000


ValueError: Cannot feed value of shape (1, 2, 256) for Tensor 'speaker_embeddings:0', which has shape '(?, 256)'

In [7]:
text = "This is being said in my own voice.This is being said in my own voice." #@param {type:"string"}
print("Now recording for 10 seconds, say what you will...")
# record(10)
print("Audio recording complete")
in_fpath = r"C:\Users\pedestrian\Desktop\re-voiceprint\human\lu1.m4a"
reprocessed_wav = encoder.preprocess_wav(in_fpath)
original_wav, sampling_rate = librosa.load(in_fpath)
preprocessed_wav = encoder.preprocess_wav(original_wav, sampling_rate)
embed2 = encoder.embed_utterance(preprocessed_wav)
# print("Synthesizing new audio...")
# with io.capture_output() as captured:
#   specs = synthesizer.synthesize_spectrograms([text], [embed])
# generated_wav = vocoder.infer_waveform(specs[0])
# generated_wav = np.pad(generated_wav, (0, synthesizer.sample_rate), mode="constant")
# display(Audio(generated_wav, rate=synthesizer.sample_rate))

Now recording for 10 seconds, say what you will...
Audio recording complete


In [15]:
embed1

array([4.12342362e-02, 4.32683118e-02, 0.00000000e+00, 0.00000000e+00,
       2.65611950e-02, 8.33244063e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.13994826e-02, 4.28802483e-02, 2.06909910e-01,
       1.08816579e-01, 1.14724077e-02, 1.53335007e-02, 4.31271605e-02,
       7.29819462e-02, 5.09995148e-02, 0.00000000e+00, 0.00000000e+00,
       5.31005207e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 5.60861118e-02, 0.00000000e+00, 5.08742826e-03,
       0.00000000e+00, 0.00000000e+00, 6.25672191e-02, 9.68943536e-02,
       2.79527344e-02, 2.25985218e-02, 8.75157341e-02, 7.06613660e-02,
       4.71985899e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.19661298e-02, 1.89696755e-02, 8.73973370e-02,
       7.96950534e-02, 2.81385016e-02, 0.00000000e+00, 6.67545199e-02,
       7.59264752e-02, 2.41308026e-02, 0.00000000e+00, 8.74618664e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.51358573e-02,
      

In [8]:
embed2

(array([0.00000000e+00, 2.86098178e-02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.35659089e-02, 0.00000000e+00, 3.98167260e-02,
        1.74793527e-02, 6.41821846e-02, 1.42663389e-01, 1.20784439e-01,
        4.01942022e-02, 0.00000000e+00, 0.00000000e+00, 1.32044613e-01,
        6.08208887e-02, 3.78391966e-02, 4.15784027e-03, 0.00000000e+00,
        0.00000000e+00, 1.73344582e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.82874137e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 6.85061142e-02, 0.00000000e+00,
        2.02664852e-01, 0.00000000e+00, 3.74633558e-02, 6.56281561e-02,
        4.45506573e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 8.96910280e-02, 4.57912460e-02, 1.02906786e-01,
        9.66149382e-03, 7.73228556e-02, 0.00000000e+00, 8.63497332e-02,
        6.77320585e-02, 9.18106958e-02, 0.00000000e+00, 1.25967160e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.120729

In [18]:
np.linalg.norm(embed1-embed2)

0.6525545

In [5]:
test="This is being said in my own voice. This is being said in my own voice.This is being said in my own voice. This is being said in my own voice.This is being said in my own voice. This is being said in my own voice.
This is being said in my own voice. This is being said in my own voice."

array([[-3.9524724, -3.9423158, -3.8223953, ..., -3.85504  , -3.8421283,
        -3.850272 ],
       [-3.9607759, -3.944692 , -3.8018734, ..., -3.8699708, -3.8319888,
        -3.8736413],
       [-3.9504614, -3.950419 , -3.8631356, ..., -3.8377397, -3.812024 ,
        -3.839312 ],
       ...,
       [-3.9695323, -4.023772 , -3.965344 , ..., -0.7730428, -1.3192565,
        -2.0053086],
       [-3.955943 , -3.9954484, -3.9383178, ..., -0.6918752, -1.2454225,
        -1.9566786],
       [-3.9341848, -3.9809728, -3.9289749, ..., -0.6959319, -1.2485704,
        -1.9640918]], dtype=float32)

In [17]:
sy=["_","~"]+list( "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\'\"(),-.:;? ")

In [19]:
sy[47]

't'